# Generated by Django 3.2.8 on 2023-12-18 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cellular_technology',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guarantee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water_and_dust_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='start',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Start'),
            preserve_default=False,
        ),
    ]
