# Generated by Django 3.2.8 on 2023-12-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231218_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='time',
        ),
    ]
