# Generated by Django 3.2.8 on 2023-12-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20231220_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='time',
            new_name='title',
        ),
    ]
