# Generated by Django 3.2.8 on 2023-12-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_time_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='where',
            new_name='brand',
        ),
    ]
