# Generated by Django 3.2.8 on 2023-12-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_where_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form_factor',
            field=models.CharField(default=1958, max_length=100),
            preserve_default=False,
        ),
    ]
